# Settings
## Congregation name and location (as to print in result file)
congregationName : Anytown West (Anytown)
coordinatorText : John Doe, 123 Maple Street. Anytown, PA 17101, 0123/12345678
## Signature location string
place: Anytown

## Comma separated list of name that will be skipped in report creation
#excludedNames : John Doe,Jane Doe

## Name replacements, usefull for example if bank account report contains mutliple names for 
## same user, but report only one report must be created of all versions
#nameReplacements :
#  John-Michael Doe : John Doe
#  Janice Doe : Jane Doe 

## Workarround. Set names of your self added form fields
customSumField1 : field-name 
customSumField2 : field-name2